/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export interface UserDTO {
    username?: string | undefined;
    token?: string | undefined;
}

export interface RegisterDTO {
    username: string;
    password: string;
}

export interface LoginDTO {
    username: string;
    password: string;
}

export interface AppUser {
    id: number;
    userName?: string | undefined;
    passwordHash?: string | undefined;
    passwordSalt?: string | undefined;
    dateOfBirth: Date;
    handle?: string | undefined;
    created: Date;
    lastActive: Date;
    gender?: string | undefined;
    summary?: string | undefined;
    interestedIn?: string | undefined;
    interests?: string | undefined;
    city?: string | undefined;
    country?: string | undefined;
    photos?: Photo[] | undefined;
}

export interface Photo {
    id: number;
    url?: string | undefined;
    isMain: boolean;
    publicId?: string | undefined;
    appUser?: AppUser | undefined;
    appUserId: number;
}

export interface MemberDTO {
    id: number;
    username?: string | undefined;
    photoUrl?: string | undefined;
    age: number;
    handle?: string | undefined;
    created: Date;
    lastActive: Date;
    gender?: string | undefined;
    summary?: string | undefined;
    interestedIn?: string | undefined;
    interests?: string | undefined;
    city?: string | undefined;
    country?: string | undefined;
    photos?: PhotoDTO[] | undefined;
}

export interface PhotoDTO {
    id: number;
    url?: string | undefined;
    isMain: boolean;
}